# Project information
site_name: ML.ENERGY Blog
site_url: https://ml.energy/blog
site_author: Jae-Won Chung
site_description: ML.ENERGY research & tech blog
edit_uri: ""

copyright: Copyright &copy; 2023 Jae-Won Chung

theme:
  name: material
  custom_dir: docs/overrides
  icon:
    logo: material/lightning-bolt
  favicon: assets/img/favicon.ico
  features:
    - search.suggest
    - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    - content.code.copy
  palette:
    - scheme: slate
      primary: ml.energy
      accent: ml.energy
      toggle:
        icon: fontawesome/solid/sun
        name: Switch to light mode
    - scheme: default
      primary: ml.energy
      accent: ml.energy
      toggle:
        icon: fontawesome/regular/moon
        name: Switch to dark mode

plugins:
  - typeset
  - meta
  - search
  - tags
  - social:
      cards_dir: assets/img/social
      cards_layout_options:
        background_color: "#23d175"
        color: "#000000"
  - blog:
      blog_dir: .
      post_readtime: false
      post_url_format: "{categories}/{slug}"
      post_url_max_categories: 2
  - rss:
      match_path: posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories

markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - index.md

extra:
  social:
    - icon: material/rss
      link: https://ml.energy/blog/feed_rss_created.xml

extra_css:
  - assets/css/color.css
  - assets/css/custom.css

extra_javascript:
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
