authors:
  jaywonchung:
    name: Jae-Won Chung
    description: PhD Student
    avatar: https://ml.energy/assets/img/members/jae-won.jpg
  michahn01:
    name: Jisang (Michael) Ahn
    description: Undergrad
    avatar: assets/img/pfp/michahn01.png
